#!/bin/bash
##################################################
# AUTHOR: Neo <netkiller@msn.com>
# WEBSITE: http://www.netkiller.cn
# Description: Netkiller state statistics
# Note：Zabbix 3.2
# DateTime: 2016-12-09
##################################################
TTL=1
CACHE=/dev/shm/tcpstat.cch
##################################################

if [ -f ${CACHE} ]; then
	find ${CACHE} -type f -mmin +${TTL} -delete
fi

if [ ! -f ${CACHE} ]; then
	ss -ant | awk 'BEGIN {stats["CLOSE-WAIT"]=0;stats["ESTAB"]=0;stats["FIN-WAIT-1"]=0;stats["FIN-WAIT-2"]=0;stats["LAST-ACK"]=0;stats["SYN-RECV"]=0;stats["SYN-SENT"]=0;stats["TIME-WAIT"]=0} {++stats[$1]} END {for(a in stats) print a, stats[a]}' > ${CACHE}
fi

grep $1 ${CACHE} | cut -d " " -f2